### ISSUE TITLE
Make PageKite use a unique token per gateway instead of a hardcoded secret

### ISSUE THREAD

**Issue by andrenatal** [WebThingsIO/registration_server#11]
Pagekite secret is harcoded and the same to every user. We should change use the token.

**Comment by mrstegeman** [comment]
There doesn't seem to be a way to do this in our current setup without updating the PageKite config and restarting every time a gateway is registered.

**Comment by mrstegeman** [comment]
PageKite can apparently do authentication based on a DNS lookup, but it's completely undocumented. However, that looks like the best path forward.

See `AuthThread` in `pk.py`.

**Comment by mrstegeman** [comment]
As it turns out, this is already implemented in the server! We just weren't using it.
