### ISSUE TITLE
Start using LE staging in our staging environment

### ISSUE THREAD

**Issue by andrenatal** [WebThingsIO/registration_server#30]

**Comment by hobinjk** [comment]
https://letsencrypt.org/docs/staging-environment/

**Comment by andrenatal** [comment]
Actually this should be changed in the client, and not here. One should change here:

https://github.com/mozilla-iot/gateway/blob/master/src/controllers/settings_controller.js#L88

to use `greenlock.stagingServerUrl` instead `greenlock.productionServerUrl` 

Will close this and open in the gateway repo
