### ISSUE TITLE
Move database from SQLite to Amazon RDS to make it more reliable

### ISSUE THREAD

**Issue by andrenatal** [WebThingsIO/registration_server#39]

**Comment by andrenatal** [comment]
I think this is very important, we are currently relying on a flat file and use a more reliable db would be a wise decision. @mrstegeman Could you take a look on this, please?

**Comment by mrstegeman** [comment]
Amazon Aurora looks promising. Should be able to use a standard mysql library to connect, such as: https://github.com/blackbeam/rust-mysql-simple

**Comment by andrenatal** [comment]
That's very cool!

**Comment by mrstegeman** [comment]
Done! Databases are now using Amazon Aurora MySQL.

**Comment by andrenatal** [comment]
Very nice @mrstegeman! Thanks for that!
