### ISSUE TITLE
Error issuing certificate

### ISSUE THREAD

**Issue by benfrancis** [WebThingsIO/registration_server#83]
STR:

* Flash latest OpenWrt image (openwrt-rpi-0.8.1-2.img.zip)
* Try to register a subdomain during first time setup

Expected:
* Successful registration, redirected to new subdomain

Actual:
* POST gets a 400 response with the following error message:

`Error issuing certificate - FetchError: request to https://api.mozilla-iot.org:8443/subscribe?name=tola2&email=ben@tola.me.uk failed, reason: getaddrinfo EAI_AGAIN api.mozilla-iot.org:8443`

Is this maybe a DNS problem?

See also: #20

**Comment by mrstegeman** [comment]
That indicates a DNS issue. Try:

`dig api.mozilla-iot.org`

**Comment by benfrancis** [comment]
That seems to resolve, but I've now completed first time setup.

I'm wondering whether it just hadn't managed to get an outbound connection to the Internet from my router via Ethernet for some reason. I'll try first time setup again later.

**Comment by benfrancis** [comment]
I went through first time setup again and it worked. I'm pretty certain this was a user error on my part, I don't think the gateway had an outbound connection to the Internet because of the way my network was configured. My bad!

I'll close this issue, all we can really do in this situation is provide an informative error message! I've filed https://github.com/mozilla-iot/gateway/issues/1936
