### ISSUE TITLE
Need list of registered subdomain from Registration server

### ISSUE THREAD

**Issue by viren-moradiya** [WebThingsIO/registration_server#87]
Hello Folks,

Good day to you!
I am looking for one solution regarding to get list of registered subdomain by calling API to registration server.

Currently Registration server is not providing any API to get registered subdomain list.
Can registration server provide this detail by exposing API or we required code changes to expose API and this detail list?

Looking forward for your expert advice.

Thanks,
Viren

**Comment by mrstegeman** [comment]
Are you looking to get a list of _all_ registered subdomains, or subdomains registered to a specific account?

**Comment by viren-moradiya** [comment]
Hello @mrstegeman,

I am looking for to get a list of all registered subdomains.

**Comment by mrstegeman** [comment]
That would require a sort of admin account to be added to the registration server, as there is currently no concept of that. It's pretty straightforward to get a list from the database, though.

**Comment by viren-moradiya** [comment]
@mrstegeman Can you suggest me piece of code area to get this list?

**Comment by mrstegeman** [comment]
If you connect to your database from the command line (or a script), you can do `SELECT name FROM domains`.
