### ISSUE TITLE
To make registration-server work without exposing port 53 to the internet

### ISSUE THREAD

**Issue by viren-moradiya** [WebThingsIO/registration_server#88]
Hi Team,

Can the registration and tunnelling process work without exposing the port 53 to the public internet? 
And if this is not possible, can we separate out DNS server from the registration server?

Thanks,
Viren

**Comment by mrstegeman** [comment]
No, it cannot. The way PageKite is set up in the registration server requires the DNS server to be public. They could potentially be separated, but the registration server needs to communicate directly with the PowerDNS server, which is currently done via a Unix domain socket.

**Comment by abhijitnathwani** [comment]
Hi @mrstegeman ,

If we could potentially separate out PowerDNS and the registration server, will the PowerDNS server need port 53 exposed to public ?

**Comment by mrstegeman** [comment]
Yes, it would still have to be exposed to the public. The PowerDNS server serves as the authoritative nameserver for the entire domain.
