### ISSUE TITLE
Internal server error when trying to subscribe a subdomain for the second time

### ISSUE THREAD

**Issue by andrenatal** [WebThingsIO/registration_server#9]
After I run the server for the first time with a clean database, the first call to /subscription works fine, but the subsequent ones returns with an Internal server error. If I remove the database and starts again, the same behavior repeats.

**Comment by andrenatal** [comment]
Problem is [here](https://github.com/moziot/registration_server/blob/7300524d90b4a201fce3c1c5ed2d6489b1da93c2/server/src/routes.rs#L162). For some reason, this db operation is returning an error.

**Comment by andrenatal** [comment]
Found the issue. There's a unique constraint in the email field. Email can't be unique, since we'll ask user's email only after we issue the certificates.

**Comment by fabricedesre** [comment]
I don't follow... if you already have a token, you need to use it instead of calling /subscribe again.

**Comment by fabricedesre** [comment]
Ok, so you just want to register different domains with the same email & public ip. Yep we need to allow that.
