### ISSUE TITLE
Error issuing certificate - 400

### ISSUE THREAD

**Issue by RichardWhitfieldTTW** [WebThingsIO/registration_server#94]
Hi, I have flashed the latest (v 0.12.0) gateway image to my Raspberry Pi 4.  It all boots fine and I can connect to the hotspot but when I try to register for a subdomain I get the error 'Error issuing certificate. Please try again.'.  Looking into the console this is an error 400 (I have posted the error below with redacted name and email (####).

For info I tried to go beyond this by skipping the step but when I then try to look for other apps I get a blank list so I really can't do too much.

api.js:504 POST http://192.168.1.106/settings/subscribe net::ERR_ABORTED 400 (Error issuing certificate - FetchError: request to https://api.mozilla-iot.org:8443/subscribe?name=####&email=#### failed, reason: getaddrinfo EAI_AGAIN api.mozilla-iot.org api.mozilla-iot.org:8443)
setupTunnel @ api.js:504
b @ setup-subdomain.js:157

**Comment by mrstegeman** [comment]
That error indicates that your gateway doesn't have internet access (DNS resolution failed), so this is not an issue with the registration server.
